// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './type';

const SUPABASE_URL = "https://egugfxxrfidsuwtlojaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndWdmeHhyZmlkc3V3dGxvamFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTIyMjgsImV4cCI6MjA2MDc4ODIyOH0.VM7-zZ6P0J4gmDAHIbPBSz8HSrCXEMdP_bExOZh7KpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);